"""Claude Process Pool.

Manages persistent Claude CLI processes for faster response times.
Each agent gets its own process pool to maintain session isolation.

MCP configuration is handled via static config files per agent,
generated by the MCPTokenManager at startup.
"""

import asyncio
import json
import time
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from pathlib import Path

from config.logging_config import logger


class ToolNotificationThrottler:
    """Throttler per-request per notifiche tool con raggruppamento.

    Bufferizza tool calls durante l'intervallo minimo, poi invia
    una notifica raggruppata. Ogni chiamata run() deve creare una nuova istanza.
    NON condividere tra richieste o utenti diversi.
    """

    def __init__(self, min_interval: float = 1.5):
        self.min_interval = min_interval
        self.last_notification = 0.0
        self._pending: list[tuple[str, dict]] = []

    async def notify(
        self,
        callback: Callable[[str, dict], Awaitable[None]],
        tool_name: str,
        tool_input: dict,
    ) -> None:
        """Buffer notification; flush group if interval elapsed."""
        now = time.time()
        if now - self.last_notification >= self.min_interval:
            # Flush any pending + current
            if self._pending:
                await self._flush_group(callback)
            await callback(tool_name, tool_input)
            self.last_notification = time.time()
        else:
            self._pending.append((tool_name, tool_input))

    async def flush(
        self,
        callback: Callable[[str, dict], Awaitable[None]],
    ) -> None:
        """Flush remaining buffered notifications (call at end of request)."""
        if self._pending:
            await self._flush_group(callback)

    async def _flush_group(
        self,
        callback: Callable[[str, dict], Awaitable[None]],
    ) -> None:
        """Send grouped notification for buffered tools."""
        from core.tool_display import format_grouped_status

        pending = self._pending
        self._pending = []
        names = [name for name, _ in pending]
        grouped_text = format_grouped_status(names)
        # Send as a synthetic callback with the grouped text as tool_name
        # and empty input (the display text is pre-formatted)
        await callback(grouped_text, {"_grouped": True})
        self.last_notification = time.time()


@dataclass
class PooledProcess:
    """A pooled Claude CLI process."""

    process: asyncio.subprocess.Process
    agent_id: str
    model: str = ""  # Model used to spawn this process
    mcp_config_path: str | None = None  # Static config, not temp
    session_id: str | None = None  # Bound session (context isolation)
    created_at: float = field(default_factory=time.time)
    request_count: int = 0
    last_used: float = field(default_factory=time.time)
    busy: bool = False

    @property
    def age_seconds(self) -> float:
        return time.time() - self.created_at

    @property
    def idle_seconds(self) -> float:
        return time.time() - self.last_used


class ClaudeProcessPool:
    """Pool of persistent Claude CLI processes.

    Features:
    - One pool per agent for session isolation
    - Processes stay alive between requests
    - Auto-restart on crash or after max requests
    - Configurable pool size and timeouts
    """

    def __init__(
        self,
        max_processes_per_agent: int = 2,
        max_requests_per_process: int = 100,
        max_process_age_seconds: int = 3600,
        idle_timeout_seconds: int = 300,
        cleanup_interval_seconds: int = 60,
        working_dir: Path | None = None,
    ):
        self.max_processes_per_agent = max_processes_per_agent
        self.max_requests_per_process = max_requests_per_process
        self.max_process_age_seconds = max_process_age_seconds
        self.idle_timeout_seconds = idle_timeout_seconds
        self.cleanup_interval_seconds = cleanup_interval_seconds
        self.working_dir = working_dir or Path.cwd()

        self._pools: dict[str, list[PooledProcess]] = {}
        self._lock = asyncio.Lock()
        self._cleanup_task: asyncio.Task | None = None

    @staticmethod
    def _get_oauth_token() -> str | None:
        """Read OAuth access token, refreshing if expired."""
        try:
            from plugins.claude.api.routes import (
                _read_credentials_from_secrets,
                _refresh_oauth_token,
            )

            oauth_block = _read_credentials_from_secrets()
            if not oauth_block:
                return None

            refreshed = _refresh_oauth_token(oauth_block)
            if refreshed:
                oauth_block = refreshed

            return oauth_block.get("accessToken")
        except Exception as e:
            logger.debug("Could not read OAuth token from secrets: %s", e)
        return None

    async def start(self):
        """Start the pool manager."""
        self._cleanup_task = asyncio.create_task(self._cleanup_loop())
        logger.info("Claude process pool started")

    async def stop(self):
        """Stop all processes and cleanup."""
        if self._cleanup_task:
            self._cleanup_task.cancel()
            try:
                await self._cleanup_task
            except asyncio.CancelledError:
                pass

        async with self._lock:
            for agent_id, processes in self._pools.items():
                for pooled in processes:
                    await self._terminate_process(pooled)
            self._pools.clear()

        logger.info("Claude process pool stopped")

    async def _cleanup_loop(self):
        """Periodically cleanup idle and old processes."""
        while True:
            try:
                await asyncio.sleep(self.cleanup_interval_seconds)
                await self._cleanup_stale_processes()
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Error in cleanup loop: {e}")

    async def _cleanup_stale_processes(self):
        """Remove processes that are too old or idle."""
        async with self._lock:
            for agent_id, processes in list(self._pools.items()):
                to_remove = []
                for pooled in processes:
                    if pooled.busy:
                        continue

                    should_remove = (
                        pooled.age_seconds > self.max_process_age_seconds
                        or pooled.idle_seconds > self.idle_timeout_seconds
                        or pooled.request_count >= self.max_requests_per_process
                        or pooled.process.returncode is not None
                    )

                    if should_remove:
                        to_remove.append(pooled)

                for pooled in to_remove:
                    await self._terminate_process(pooled)
                    processes.remove(pooled)
                    logger.debug(
                        f"Removed stale process for {agent_id}: "
                        f"age={pooled.age_seconds:.0f}s, "
                        f"idle={pooled.idle_seconds:.0f}s, "
                        f"requests={pooled.request_count}"
                    )

    async def _terminate_process(self, pooled: PooledProcess):
        """Terminate a pooled process. Does NOT delete MCP config (static)."""
        try:
            if pooled.process.returncode is None:
                pooled.process.terminate()
                try:
                    await asyncio.wait_for(pooled.process.wait(), timeout=5.0)
                except asyncio.TimeoutError:
                    pooled.process.kill()
                    await pooled.process.wait()
        except Exception as e:
            logger.warning(f"Error terminating process: {e}")

    async def _create_process(
        self,
        agent_id: str,
        model: str,
        mcp_config_path: str | None = None,
        extra_dirs: list[Path] | None = None,
    ) -> PooledProcess:
        """Create a new Claude CLI process.

        Uses the static MCP config file generated by the MCPTokenManager.
        """
        cmd = [
            "claude",
            "-p",
            "--verbose",  # Required for stream-json output
            "--input-format",
            "stream-json",
            "--output-format",
            "stream-json",
            "--include-partial-messages",  # Emit content_block_delta for streaming
            "--model",
            model,
        ]

        if mcp_config_path:
            cmd.extend(["--mcp-config", mcp_config_path, "--strict-mcp-config"])

        # Add permissions from settings (file ops + gateway wildcard from
        # claude_settings) AND the agent-specific MCP allowlist from the
        # token manager. Without the token-manager addition every tool
        # call fires the manual-approval popup, breaking non-interactive
        # channels (WebChat, Telegram) where no human can click Allow.
        all_perms: list[str] = []
        try:
            from core.system_config import SystemConfig

            settings = SystemConfig.get_param_sync("claude_settings")
            if settings:
                all_perms = list(settings.get("permissions", {}).get("allow", []) or [])
        except Exception:
            pass

        try:
            from core.mcp_token_manager import get_mcp_token_manager

            tm = get_mcp_token_manager()
            if tm:
                all_perms.extend(tm.get_allowed_tools(agent_id))
        except Exception:
            pass

        if all_perms:
            cmd.extend(["--allowedTools"] + all_perms)

        if extra_dirs:
            for d in extra_dirs:
                if d.exists():
                    cmd.extend(["--add-dir", str(d)])

        # Pass OAuth token via env var — no credentials file needed.
        # The CLI reads CLAUDE_CODE_OAUTH_TOKEN directly from the environment.
        import os

        env = {**os.environ}
        token = self._get_oauth_token()
        if token:
            env["CLAUDE_CODE_OAUTH_TOKEN"] = token

        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=self.working_dir,
            env=env,
            limit=4
            * 1024
            * 1024,  # 4MB buffer for large MCP responses (Playwright snapshots)
        )

        pooled = PooledProcess(
            process=process,
            agent_id=agent_id,
            model=model,
            mcp_config_path=mcp_config_path,
        )

        logger.info(
            f"Created new Claude process for {agent_id} (model={model}), pid={process.pid}"
        )
        return pooled

    async def acquire(
        self,
        agent_id: str,
        model: str,
        session_id: str | None = None,
        mcp_config_path: str | None = None,
        extra_dirs: list[Path] | None = None,
    ) -> PooledProcess:
        """Acquire a process from the pool or create a new one.

        Processes are bound to a session_id for context isolation.
        A process bound to session X will only be reused for session X.
        """
        async with self._lock:
            if agent_id not in self._pools:
                self._pools[agent_id] = []

            pool = self._pools[agent_id]

            # 1. Find process already bound to this session
            if session_id:
                for pooled in pool:
                    if (
                        pooled.session_id == session_id
                        and not pooled.busy
                        and pooled.process.returncode is None
                        and pooled.model == model
                    ):
                        pooled.busy = True
                        pooled.last_used = time.time()
                        logger.debug(
                            "Reusing session-bound process for %s sid=%s",
                            agent_id,
                            session_id[:8],
                        )
                        return pooled

            # 2. Find unbound process (no session yet)
            for pooled in pool:
                if (
                    pooled.session_id is None
                    and not pooled.busy
                    and pooled.process.returncode is None
                    and pooled.model == model
                ):
                    pooled.session_id = session_id
                    pooled.busy = True
                    pooled.last_used = time.time()
                    logger.debug(
                        "Binding fresh process to %s sid=%s",
                        agent_id,
                        session_id[:8] if session_id else "none",
                    )
                    return pooled

            # 3. Create new process if pool has room
            if len(pool) < self.max_processes_per_agent:
                pooled = await self._create_process(
                    agent_id, model, mcp_config_path, extra_dirs
                )
                pooled.session_id = session_id
                pooled.busy = True
                pool.append(pooled)
                return pooled

            # 4. Pool full — reclaim oldest idle process bound to a different session
            oldest = None
            for pooled in pool:
                if (
                    not pooled.busy
                    and pooled.process.returncode is None
                    and pooled.model == model
                    and pooled.session_id != session_id
                ):
                    if oldest is None or pooled.last_used < oldest.last_used:
                        oldest = pooled

            if oldest:
                logger.info(
                    "Pool full for %s — recycling idle process (old sid=%s)",
                    agent_id,
                    oldest.session_id[:8] if oldest.session_id else "none",
                )
                await self._terminate_process(oldest)
                pool.remove(oldest)
                pooled = await self._create_process(
                    agent_id, model, mcp_config_path, extra_dirs
                )
                pooled.session_id = session_id
                pooled.busy = True
                pool.append(pooled)
                return pooled

            logger.warning(
                "Pool full for %s, all busy — waiting for available process",
                agent_id,
            )

        await asyncio.sleep(0.5)
        return await self.acquire(
            agent_id, model, session_id, mcp_config_path, extra_dirs
        )

    def release(self, pooled: PooledProcess):
        """Release a process back to the pool."""
        pooled.busy = False
        pooled.request_count += 1
        pooled.last_used = time.time()

    async def destroy(self, pooled: PooledProcess):
        """Terminate and remove a process from the pool.

        Use after a timeout or unrecoverable error — the process may be
        stuck mid-operation and cannot be safely reused.
        """
        async with self._lock:
            for processes in self._pools.values():
                if pooled in processes:
                    processes.remove(pooled)
                    break
        await self._terminate_process(pooled)
        logger.info(
            "Pool: destroyed process for agent=%s session=%s (pid=%s)",
            pooled.agent_id,
            pooled.session_id,
            pooled.process.pid if pooled.process else "?",
        )

    async def send_prompt(
        self,
        pooled: PooledProcess,
        prompt: str,
        session_id: str | None = None,
        timeout: float = 600.0,
        tool_callback: Callable[[str, dict], Awaitable[None]] | None = None,
        tool_config: dict | None = None,
        stream_callback: Callable[[str], Awaitable[None]] | None = None,
    ) -> dict:
        """Send a prompt to a pooled process and get response.

        Uses stream-json protocol:
        Input: {"type":"user","message":{"role":"user","content":"..."}}
        Output:
          - {"type":"system","subtype":"init",...} - initialization
          - {"type":"assistant","message":{...}} - assistant response
          - {"type":"tool_result",...} - tool execution result (top-level)
          - {"type":"result","subtype":"success",...} - final result

        Args:
            pooled: The pooled process to send to
            prompt: The prompt text
            session_id: Optional session ID to resume
            timeout: Request timeout in seconds
            tool_callback: Optional callback called when a tool is used.
                          Signature: async def callback(tool_name: str, tool_input: dict)
            tool_config: Optional dict controlling logging/notification behavior.
                        Keys: log_calls, log_input, log_output, notify (all bool, default True)
            stream_callback: Optional callback called with accumulated text as Claude
                            generates it (inter-turn streaming). Called with the full
                            text generated so far (not deltas).
                            Signature: async def callback(text: str)
        """
        if pooled.process.returncode is not None:
            raise RuntimeError("Process has terminated")

        # Resolve tool_config defaults
        tc = tool_config or {}
        log_calls = tc.get("log_calls", True)
        log_input = tc.get("log_input", True)
        log_output = tc.get("log_output", True)
        notify = tc.get("notify", True)

        # Build request in stream-json format
        request = {
            "type": "user",
            "message": {
                "role": "user",
                "content": prompt,
            },
        }

        request_line = json.dumps(request) + "\n"
        pooled.process.stdin.write(request_line.encode())
        await pooled.process.stdin.drain()

        response_parts = []
        final_response = None
        assistant_message = None
        init_data = None

        # Per-request throttler for tool notifications
        throttler = ToolNotificationThrottler(min_interval=1.5)

        # Track tool_use timing for tool_result correlation
        tool_timings: dict[str, tuple[str, float]] = {}
        # Ordered list to correlate results when tool_use_id is unavailable
        tool_order: list[str] = []

        # Track last streamed text to avoid duplicate callbacks
        _last_streamed_text = ""

        def _log_tool_result(tool_name: str, duration: float, is_error: bool, output):
            """Log a tool result with timing and optional output."""
            if is_error:
                logger.warning(f"Tool {tool_name} failed in {duration:.2f}s")
            elif log_calls:
                logger.info(f"Tool {tool_name} completed in {duration:.2f}s")

            if log_output and output:
                output_str = str(output)
                if len(output_str) > 500:
                    logger.debug(f"Tool output ({tool_name}): {output_str[:500]}...")
                elif output_str:
                    logger.debug(f"Tool output ({tool_name}): {output_str}")

        try:
            async with asyncio.timeout(timeout):
                while True:
                    line = await pooled.process.stdout.readline()
                    if not line:
                        break

                    try:
                        data = json.loads(line.decode())
                        response_parts.append(data)

                        msg_type = data.get("type")

                        if msg_type == "system" and data.get("subtype") == "init":
                            init_data = data
                        elif msg_type == "assistant":
                            assistant_message = data

                            # Intercept tool_use messages
                            content = data.get("message", {}).get("content", [])
                            for block in content:
                                if block.get("type") == "tool_use":
                                    tool_name = block.get("name", "unknown")
                                    tool_input = block.get("input", {})
                                    tool_use_id = block.get("id", "")

                                    # Track timing for tool_result correlation
                                    now = time.time()
                                    if tool_use_id:
                                        tool_timings[tool_use_id] = (tool_name, now)
                                    tool_order.append(tool_use_id or tool_name)

                                    # Log tool call (conditioned on config flags)
                                    if log_calls:
                                        logger.info(f"MCP Tool called: {tool_name}")
                                    if log_input:
                                        input_str = str(tool_input)
                                        if len(input_str) > 1000:
                                            logger.debug(
                                                f"Tool input: {input_str[:1000]}..."
                                            )
                                        else:
                                            logger.debug(f"Tool input: {input_str}")

                                    # Callback to notify user (with error handling and timeout)
                                    if notify and tool_callback:
                                        try:
                                            await asyncio.wait_for(
                                                throttler.notify(
                                                    tool_callback, tool_name, tool_input
                                                ),
                                                timeout=2.0,
                                            )
                                        except asyncio.TimeoutError:
                                            logger.debug(
                                                f"Tool callback timed out for {tool_name}"
                                            )
                                        except Exception as e:
                                            logger.warning(f"Tool callback failed: {e}")
                                            # Do NOT re-raise - must not interrupt streaming

                            # Stream text to callback (inter-turn: full text so far)
                            if stream_callback:
                                text_parts = [
                                    c.get("text", "")
                                    for c in content
                                    if c.get("type") == "text"
                                ]
                                new_text = "".join(text_parts)
                                if new_text and new_text != _last_streamed_text:
                                    _last_streamed_text = new_text
                                    try:
                                        await stream_callback(new_text)
                                    except Exception:
                                        pass  # never interrupt streaming

                        elif msg_type == "stream_event":
                            # Incremental text deltas from --include-partial-messages
                            event = data.get("event", {})
                            event_type = event.get("type", "")
                            if event_type == "content_block_start":
                                # New content block: reset accumulated text for this turn
                                cb = event.get("content_block", {})
                                if cb.get("type") == "text":
                                    _last_streamed_text = ""
                            elif event_type == "content_block_delta":
                                delta = event.get("delta", {})
                                if delta.get("type") == "text_delta":
                                    delta_text = delta.get("text", "")
                                    if delta_text and stream_callback:
                                        _last_streamed_text += delta_text
                                        try:
                                            await stream_callback(_last_streamed_text)
                                        except Exception:
                                            pass

                        elif msg_type == "tool_result":
                            # Top-level tool_result (stream-json format)
                            tool_use_id = data.get("tool_use_id", "")
                            is_error = data.get("is_error", False)
                            output = data.get("output", data.get("content", ""))

                            if tool_use_id and tool_use_id in tool_timings:
                                t_name, t_start = tool_timings.pop(tool_use_id)
                                _log_tool_result(
                                    t_name, time.time() - t_start, is_error, output
                                )
                            elif tool_order:
                                # Fallback: correlate by order
                                key = tool_order.pop(0)
                                if key in tool_timings:
                                    t_name, t_start = tool_timings.pop(key)
                                    _log_tool_result(
                                        t_name, time.time() - t_start, is_error, output
                                    )

                        elif msg_type == "user":
                            # Alternative format: tool_result nested in user message
                            content = data.get("message", {}).get("content", [])
                            if not isinstance(content, list):
                                content = [content] if content else []
                            for block in content:
                                if not isinstance(block, dict):
                                    continue
                                if block.get("type") == "tool_result":
                                    tool_use_id = block.get("tool_use_id", "")
                                    is_error = block.get("is_error", False)
                                    output = block.get("content", "")
                                    if isinstance(output, list):
                                        output = " ".join(
                                            str(b.get("text", ""))
                                            for b in output
                                            if isinstance(b, dict)
                                        )

                                    if tool_use_id and tool_use_id in tool_timings:
                                        t_name, t_start = tool_timings.pop(tool_use_id)
                                        _log_tool_result(
                                            t_name,
                                            time.time() - t_start,
                                            is_error,
                                            output,
                                        )

                        elif msg_type == "result":
                            final_response = data
                            break

                    except json.JSONDecodeError:
                        logger.debug(f"Non-JSON output: {line.decode()[:100]}")

        except asyncio.TimeoutError:
            raise asyncio.TimeoutError(f"Request timed out after {timeout}s")

        # Flush any remaining buffered tool notifications
        if notify and tool_callback:
            try:
                await asyncio.wait_for(throttler.flush(tool_callback), timeout=2.0)
            except Exception:
                pass

        # Build response dict
        result = {
            "init": init_data,
            "assistant": assistant_message,
            "result": final_response,
            "raw_parts": response_parts,
        }

        # Extract text from assistant message
        if assistant_message:
            msg = assistant_message.get("message", {})
            content = msg.get("content", [])
            if content and isinstance(content, list):
                text_parts = [
                    c.get("text", "") for c in content if c.get("type") == "text"
                ]
                result["text"] = "".join(text_parts)

        # Extract metadata from result
        if final_response:
            result["session_id"] = final_response.get("session_id")
            result["cost_usd"] = final_response.get("total_cost_usd", 0.0)
            result["is_error"] = final_response.get("is_error", False)
            result["duration_ms"] = final_response.get("duration_ms", 0)

        # Propagate structured error type from CLI response
        error_type = None
        if assistant_message:
            error_type = assistant_message.get("error")
        if not error_type and final_response:
            error_type = final_response.get("error_type") or final_response.get("error")
        if error_type:
            result["error_type"] = error_type

        return result


_pool: ClaudeProcessPool | None = None


def get_pool() -> ClaudeProcessPool:
    """Get the global process pool instance."""
    global _pool
    if _pool is None:
        from config.settings import BASE_DIR

        _pool = ClaudeProcessPool(working_dir=BASE_DIR)
    return _pool


async def initialize_pool():
    """Initialize the global process pool."""
    pool = get_pool()
    await pool.start()


async def shutdown_pool():
    """Shutdown the global process pool."""
    global _pool
    if _pool:
        await _pool.stop()
        _pool = None
